### ISSUE TITLE
Considering install Google Play licensing library

### ISSUE THREAD

**Issue by agustinsivoplas** [CircleCI-Public/cimg-android#21]
I am trying to run my test but I got this error:

![Screen Shot 2021-09-27 at 18 52 18](https://user-images.githubusercontent.com/1648539/134990789-a41bc397-c9a4-466d-87d4-0bee74eb7371.png)

Seem like if you use build tools 30.0.2 you need to install Google Play licencinsg library (not confirmed).

<img width="1021" alt="Screen Shot 2021-09-27 at 18 54 58" src="https://user-images.githubusercontent.com/1648539/134990932-712651b2-78bd-4679-a305-ea73000321b0.png">

I already have a task to accept android licenses (works in past), but with the last image does not works.

```
  accept_android_licenses:
    steps:
      - run:
          name: Accept Android Licenses
          command: |
            yes | sdkmanager --licenses || exit 0
            yes | sdkmanager --update || exit 0
```

Thanks in advance!

All the best
