### ISSUE TITLE
`Gem::FilePermissionError` when installing Ruby dependencies

### ISSUE THREAD

**Issue by AlexKrupa** [CircleCI-Public/cimg-android#43]
I encountered this problem when upgrading from a legacy Android image to the latest next-gen one.

### Problem

Running `ruby/install-deps` step from [Ruby orb](https://circleci.com/developer/orbs/orb/circleci/ruby) fails like this:
```
Gemfile.lock is bundled with bundler version 2.3.3
Installing bundler 2.3.3
Fetching bundler-2.3.3.gem
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.7.0 directory.
```

After solving this for `/var/libs/gems` it fails again for `/usr/local/bin` directory.

### Solution

Use `chmod` to grant directory permissions as described in this [StackOverflow answer](https://stackoverflow.com/a/47207118/3001432).

```yml
steps:
  # ...
  - run:
       name: Fix Ruby permissions
       command: sudo chmod -R a+w /var/lib/gems/ && sudo chmod -R a+w /usr/local/bin
  - ruby/install-deps
  # ...
```

---

I'm not sure if that's the best approach, but it solved the issue for me. Is it something that could be included in the image?

**Comment by sw360cab** [comment]
@AlexKrupa your solution works, you could even write it shorter

```yaml
steps:
  - run:
       name: Fix Ruby permissions
       command: sudo chmod -R a+w /var/lib/gems/ /usr/local/bin
```
